version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:4173"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
